version: '3.8'
services:
    keycloak:
        depends_on: 
            - keycloak-db
        build:
            dockerfile: Dockerfile.keycloak
            context: .
        environment: 
            DB_VENDOR: POSTGRES
            DB_ADDR: keycloak-db
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            PROXY_ADDRESS_FORWARDING: 'true'
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
    keycloak-db:
        image: postgres:13-alpine
        volumes:
            - /Users/arlindne/primboard/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
    nginx:
        depends_on:
            # - node
            - gateway
        image: nginx:1.19.4-alpine
        volumes:
            - ${PWD}/utils/nginx.conf:/etc/nginx/nginx.conf:rw
            - /Users/arlindne/primboard/letsencrypt/:/etc/letsencrypt/:ro
            - /Users/arlindne/primboard/node/etc/nginx/logs:/etc/nginx/logs:rw
        environment: 
            - proxy-address-forwarding=true
        ports:
            - 80:80
            - 443:443
    gateway:
        depends_on: 
            - keycloak
        build:
            dockerfile: Dockerfile.gateway
            context: .
            target: "${COMPOSE_TARGET}"
        environment:
            - PORT=8765
            - MONGO_URL=mongodb://primboardapi:Start123@10.101.1.1:27017/primboard
            - DATABASE_NAME=primboard
            - CERTIFICATES=/certs
            - CA_CERT=/certs/ca-cert.pem
            - TLS_INSECURE=false
            - COOKIE_PATH=/
            - COOKIE_HTTP_ONLY=false
            - COOKIE_SAME_SITE=2
            - COOKIE_SECURE=true
            - COOKIE_TOKEN_TITLE=stoken
            - COOKIE_DOMAIN=10.101.1.8
            - HTTP=true
            - KEYCLOAK_URL=https://10.101.1.8/keycloak
            - KEYCLOAK_REALM=primboard
            - KEYCLOAK_CLIENT_ID=primboard-gateway
            - KEYCLOAK_SECRET=d73496b6-4915-4314-8acd-4bfcbdc6e40f
            - ALLOWED_ORIGINS=https://10.101.1.8:4200
            - TAG_PREVIEW_LIMIT=5
            - SESSION_ROTATION=false
            - DEFAULT_MEDIA_PAGE_SIZE=30
            - INVITE_VALIDITY=3
        volumes:
            - /Users/arlindne/minica/myCert:/certs/ca-cert.pem
    node:
        depends_on:
            - gateway
        build:
            dockerfile: Dockerfile.node
            context: .
            target: "${COMPOSE_TARGET}"
        environment:
            - BASEPATH=/data
            - TARGETPATH=/share
            - CA_CERT=/certs/ca-cert.pem
            - GATEWAY_URL=http://gateway:8765
            - KEYCLOAK_URL=https://10.101.1.8/keycloak
            - KEYCLOAK_REALM=primboard
            - KEYCLOAK_CLIENT_ID=5f9eacd7e2c078a2988b9901
            - KEYCLOAK_SECRET=fab4f5b2-c33f-4ddf-8d77-187c4ae8cbb1
            - PORT=8766
            - ALLOWED_ORIGINS=http://gateway:8765;https://10.101.1.8:4200
            - NODE_AUTH_ID=5f9eacd7e2c078a2988b9901
            - NODE_AUTH_SECRET=sdfnsdfjhsduifhsdiufhsdiuofhjsdi
        volumes:
            - /Users/arlindne/primboard/node/data:/data:rw
            - /Users/arlindne/primboard/node/share:/share:rw
            - /Users/arlindne/minica/myCert:/certs/ca-cert.pem
            - /Users/arlindne/primboard/node/etc/nginx/locations:/etc/nginx/locations:rw