# syntax=docker/dockerfile:1.0-experimental

FROM jrottenberg/ffmpeg:4.1-alpine AS base

COPY --from=golang:1.15.5-alpine /usr/local/go/ /usr/local/go/
 
ENV PATH="/usr/local/go/bin:${PATH}"

RUN apk update && apk add build-base pkgconfig
# pkgconfig ffmpeg

ENV PKG_CONFIG_PATH=$HOME/ffmpeg_build/lib/pkgconfig

WORKDIR /src

COPY go.* .

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

FROM base AS build

ARG TARGETOS
ARG TARGETARCH
RUN --mount=target=. \
    --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /node-api cmd/primboard-api-node/main.go

RUN chmod +x /node-api

FROM jrottenberg/ffmpeg:4.1-alpine AS run

COPY --from=build /node-api .

EXPOSE 8766
ENTRYPOINT [ "/usr/bin/env" ]
CMD [ "/node-api", "-env" ]