version: '3.8'
services:
    keycloak:
        depends_on: 
            - keycloak-db
        build:
            dockerfile: Dockerfile.keycloak
            context: .
            target: "${COMPOSE_TARGET}"
        environment: 
            DB_VENDOR: POSTGRES
            DB_ADDR: keycloak-db
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: password
            PROXY_ADDRESS_FORWARDING: 'true'
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        expose:
            - 8080
    keycloak-db:
        image: postgres:13-alpine
        volumes:
            - /Users/arlindne/primboard/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: password
    nginx:
        depends_on:
            - node
            - gateway
        build:
            dockerfile: Dockerfile.nginx
            context: .
            target: "${COMPOSE_TARGET}"
        volumes:
            - ${PWD}/utils/nginx.conf:/etc/nginx/nginx.conf:rw
            - ${PWD}/utils/10-incron-watch:/etc/incron.d/10-incron-watch:ro
            - /Users/arlindne/primboard/letsencrypt/:/etc/letsencrypt/:ro
            - /Users/arlindne/primboard/node/data:/data:ro
            - /Users/arlindne/primboard/node/etc/nginx/locations:/etc/nginx/locations:rw
            - /Users/arlindne/primboard/node/etc/nginx/cache/:/etc/nginx/cache:rw
            - /Users/arlindne/primboard/node/etc/nginx/logs:/etc/nginx/logs:rw
        environment: 
            - proxy-address-forwarding=true
        ports:
            - 80:80
            - 443:443
    gateway:
        depends_on: 
            - keycloak
        build:
            dockerfile: Dockerfile.gateway
            context: .
            target: "${COMPOSE_TARGET}"
        environment:
            - PORT=8765
            - MONGO_URL=mongodb://primboardapi:Start123@10.101.1.1:27017/primboard
            - DATABASE_NAME=primboard
            - CERTIFICATES=/certs
            - CA_CERT=/certs/ca-cert.pem
            - TLS_INSECURE=false
            - COOKIE_PATH=/
            - COOKIE_HTTP_ONLY=false
            - COOKIE_SAME_SITE=2
            - COOKIE_SECURE=true
            - COOKIE_TOKEN_TITLE=stoken
            - COOKIE_DOMAIN=10.101.1.8
            - HTTP=true
            - ALLOWED_ORIGINS=http=//localhost:4200;https://localhost:4200;http://172.17.0.1:4200;http://10.101.1.2:4200;https://10.101.1.2:4200;https://10.101.1.8:4200;
            - TAG_PREVIEW_LIMIT=5
            - SESSION_ROTATION=false
            - DEFAULT_MEDIA_PAGE_SIZE=30
            - INVITE_VALIDITY=3
        expose: 
            - 8765
        volumes:
            - /Users/arlindne/minica/myCert:/certs/ca-cert.pem
    node:
        depends_on:
            - gateway
        build:
            dockerfile: Dockerfile.node
            context: .
            target: "${COMPOSE_TARGET}"
        environment:
            - BASEPATH=/data
            - TARGETPATH=/share
            - CA_CERT=/certs/ca-cert.pem
            - GATEWAY_URL=http://gateway:8765
            - PORT=8766
            - ALLOWED_ORIGINS=http://gateway:8765
            - NODE_AUTH_ID=5f9eacd7e2c078a2988b9901
            - NODE_AUTH_SECRET=sdfnsdfjhsduifhsdiufhsdiuofhjsdi
        expose:
            - 8766
        volumes:
            - /Users/arlindne/primboard/node/data:/data:rw
            - /Users/arlindne/primboard/node/share:/share:rw
            - /Users/arlindne/minica/myCert:/certs/ca-cert.pem
            - /Users/arlindne/primboard/node/etc/nginx/locations:/etc/nginx/locations:rw