/*
 * PrImBoard
 *
 * PrImBoard (Private Image Board) can be best described as an image board for all the picures and videos you have taken. You can invite users to the board and share specific images with them or your family members!
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	sw "github.com/mirisbowring/PrImBoard/go"
)

func main() {
	log.Printf("Server started")

	a := sw.App{}
	a.Initialize()
	a.Run(":8765")
}
