/*
 * PrImBoard
 *
 * PrImBoard (Private Image Board) can be best described as an image board for all the picures and videos you have taken. You can invite Medias to the board and share specific images with them or your family members!
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"net/http"
	"time"
	"github.com/gorilla/mux"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

/*
 * Handles the webrequest for Media creation
 */
 func (a *App) AddMedia(w http.ResponseWriter, r *http.Request) {
	var m Media
	// decode request into model
	decoder := json.NewDecoder(r.Body)
	if err := decoder.Decode(&m); err != nil {
		// an decode error occured
		respondWithError(w, http.StatusBadRequest, "Invalid request payload")
		return
	}
	defer r.Body.Close()
	// url and type are mandatory
	if m.Url == "" || m.Type_ == "" {
		respondWithError(w, http.StatusBadRequest, "Url and type cannot be empty")
		return
	}
	// setting creation timestamp
	m.TimestampUpload = int64(time.Now().Unix())
	// try to insert model into db
	result, err := m.AddMedia(a.DB)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, err.Error())
		return
	}
	// creation successful
	respondWithJSON(w, http.StatusCreated, result)
}

/*
 * Handles the webrequest for Media deletion
 */
func (a *App) DeleteMediaById(w http.ResponseWriter, r *http.Request) {
	// parse request
	vars := mux.Vars(r)
	id, _ := primitive.ObjectIDFromHex(vars["_id"])
 	// create model by passed id
	m := Media{Id: id}
	// try to delete model
	result, err := m.DeleteMedia(a.DB)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, err.Error())
		return
	}
	// deletion successful
	respondWithJSON(w, http.StatusOK, result)
}

/*
 * Handles the webrequest for receiving all media
 */
func (a *App) GetMedia(w http.ResponseWriter, r *http.Request) {
	ms, err := GetAllMedia(a.DB)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, err.Error())
		return
	}
	respondWithJSON(w, http.StatusOK, ms)
}

/*
 * Handles the webrequest for receiving Media model by id
 */
func (a *App) GetMediaById(w http.ResponseWriter, r *http.Request) {
	// parse request
	vars := mux.Vars(r)
	id, _ := primitive.ObjectIDFromHex(vars["_id"])
	// create model by passed id
	m := Media{Id: id}
	// try to select user
	if err := m.GetMedia(a.DB); err != nil {
		switch err {
			case mongo.ErrNoDocuments:
				// model not found
				respondWithError(w, http.StatusNotFound, "Media not found")
			default:
				// another error occured
				respondWithError(w, http.StatusInternalServerError, err.Error())
		}
		return
	}
	// could select user from mongo
	respondWithJSON(w, http.StatusOK, m)
}

/*
 * Handles the webrequest for updating the Media with the passed request body
 */
func (a *App) UpdateMediaById(w http.ResponseWriter, r *http.Request) {
	// parse request
	vars := mux.Vars(r)
	id, _ := primitive.ObjectIDFromHex(vars["_id"])
	// store new model in tmp object
	var um Media
	decoder := json.NewDecoder(r.Body)
	if err :=decoder.Decode(&um); err != nil {
		// error occured during encoding
		respondWithError(w, http.StatusBadRequest, "Invalid Request payload")
		return
	}
	defer r.Body.Close()
	// trying to update model with requested body
	m := Media{Id: id}
	result, err := m.UpdateMedia(a.DB, um)
	if err != nil {
		// Error occured during update
		respondWithError(w, http.StatusInternalServerError, err.Error())
		return
	}
	// Update successful
	respondWithJSON(w, http.StatusOK, result)
}
