/*
 * PrImBoard
 *
 * PrImBoard (Private Image Board) can be best described as an image board for all the picures and videos you have taken. You can invite users to the board and share specific images with them or your family members!
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Event struct {

	Id int32 `json:"_id,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	Comments []Comment `json:"comments,omitempty"`

	Creator string `json:"creator,omitempty"`

	Groups []int32 `json:"groups,omitempty"`

	TimestampCreation int64 `json:"timestamp_creation,omitempty"`

	TimestampStart int64 `json:"timestamp_start,omitempty"`

	TimestampEnd int64 `json:"timestamp_end,omitempty"`

	Url string `json:"url,omitempty"`

	UrlThumb string `json:"url_thumb,omitempty"`
}
