/*
 * PrImBoard
 *
 * PrImBoard (Private Image Board) can be best described as an image board for all the picures and videos you have taken. You can invite users to the board and share specific images with them or your family members!
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"gopkg.in/mgo.v2/bson"
)

type UserGroup struct {
	ID                primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`
	Title             string             `json:"title,omitempty" bson:"title,omitempty"`
	Creator           string             `json:"creator,omitempty" bson:"creator,omitempty"`
	TimestampCreation int64              `json:"timestamp_creation,omitempty" bson:"timestamp_creation,omitempty"`
	Users             []string           `json:"users,omitempty" bson:"users,omitempty"`
}

// name of the mongo collection
var ugColName = "usergroup"

/*
 * Creates the model in the mongodb
 */
func (ug *UserGroup) AddUserGroup(db *mongo.Database) (*mongo.InsertOneResult, error) {
	col, ctx := GetColCtx(ugColName, db, 30)
	result, err := col.InsertOne(ctx, ug)
	return result, err
}

/*
 * Deletes the model from the mongodb
 */
func (ug *UserGroup) DeleteUserGroup(db *mongo.Database) (*mongo.DeleteResult, error) {
	col, ctx := GetColCtx(ugColName, db, 30)
	filter := bson.M{"_id": ug.ID}
	result, err := col.DeleteOne(ctx, filter)
	return result, err
}

/*
 * Returns the specified entry from the mongodb
 */
func (ug *UserGroup) GetUserGroup(db *mongo.Database) error {
	col, ctx := GetColCtx(ugColName, db, 30)
	filter := bson.M{"_id": ug.ID}
	err := col.FindOne(ctx, filter).Decode(&ug)
	return err
}

/*
 * Updates the record with the passed one
 */
func (ug *UserGroup) UpdateUserGroup(db *mongo.Database, uug UserGroup) (*mongo.UpdateResult, error) {
	col, ctx := GetColCtx(ugColName, db, 30)
	filter := bson.M{"_id": ug.ID}
	update := bson.M{"$set": uug}
	result, err := col.UpdateOne(ctx, filter, update)
	return result, err
}
