/*
 * PrImBoard
 *
 * PrImBoard (Private Image Board) can be best described as an image board for all the picures and videos you have taken. You can invite users to the board and share specific images with them or your family members!
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import(
	"go.mongodb.org/mongo-driver/mongo"
	"gopkg.in/mgo.v2/bson"
)

type User struct {
	Username string `json:"username" bson:"username"`
	FirstName string `json:"firstName,omitempty" bson:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty" bson:"lastName,omitempty"`
	Password string `json:"password,omitempty" bson:"password,omitempty"`
}

// name of the mongo collection
var userColName = "user"

/*
 * Creates the user model in the mongodb
 */
func (u *User) CreateUser(db *mongo.Database) (*mongo.InsertOneResult, error) {
	col, ctx := GetColCtx(userColName, db, 30)
	result, err := col.InsertOne(ctx, u)
	return result, err
}

/*
 * Deletes the model from the mongodb
 */
func (u *User) DeleteUser(db *mongo.Database) (*mongo.DeleteResult, error) {
	col, ctx := GetColCtx(userColName, db, 30)
	filter := bson.M{"username": u.Username}
	result, err := col.DeleteOne(ctx, filter)
	return result, err
}

/*
 * Returns the specified entry from the mongodb
 */
func (u *User) GetUser(db *mongo.Database) error {
	col, ctx := GetColCtx(userColName, db, 30)
	filter := bson.M{"username": u.Username}
	err := col.FindOne(ctx, filter).Decode(&u)
	return err
}

/*
 * Updates the record with the passed one
 */
func (u *User) UpdateUser(db *mongo.Database, uu User) (*mongo.UpdateResult, error) {
	col, ctx := GetColCtx(userColName, db, 30)
	filter := bson.M{"username": u.Username}
	update := bson.M{"$set": uu}
	result, err := col.UpdateOne(ctx, filter, update)
	return result, err
}