/*
 * PrImBoard
 *
 * PrImBoard (Private Image Board) can be best described as an image board for all the picures and videos you have taken. You can invite users to the board and share specific images with them or your family members!
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"gopkg.in/mgo.v2/bson"
)

type Event struct {
	ID                primitive.ObjectID `json:"_id,omitempty" bson:"_id,omitempty"`
	Title             string             `json:"title,omitempty" bson:"title,omitempty"`
	Description       string             `json:"description,omitempty" bson:"description,omitempty"`
	Comments          []*Comment         `json:"comments,omitempty" bson:"comments,omitempty"`
	Creator           string             `json:"creator,omitempty" bson:"creator,omitempty"`
	Groups            []int32            `json:"groups,omitempty" bson:"groups,omitempty"`
	TimestampCreation int64              `json:"timestamp_creation,omitempty" bson:"timestamp_creation,omitempty"`
	TimestampStart    int64              `json:"timestamp_start,omitempty" bson:"timestamp_start,omitempty"`
	TimestampEnd      int64              `json:"timestamp_end,omitempty" bson:"timestamp_end,omitempty"`
	Url               string             `json:"url,omitempty" bson:"url,omitempty"`
	UrlThumb          string             `json:"url_thumb,omitempty" bson:"url_thumb,omitempty"`
}

// name of the mongo collection
var eventColName = "event"

/*
 * Creates the model in the mongodb
 */
func (e *Event) AddEvent(db *mongo.Database) (*mongo.InsertOneResult, error) {
	col, ctx := GetColCtx(eventColName, db, 30)
	result, err := col.InsertOne(ctx, e)
	return result, err
}

/*
 * Deletes the model from the mongodb
 */
func (e *Event) DeleteEvent(db *mongo.Database) (*mongo.DeleteResult, error) {
	col, ctx := GetColCtx(eventColName, db, 30)
	filter := bson.M{"_id": e.ID}
	result, err := col.DeleteOne(ctx, filter)
	return result, err
}

/*
 * Returns the specified entry from the mongodb
 */
func (e *Event) GetEvent(db *mongo.Database) error {
	col, ctx := GetColCtx(eventColName, db, 30)
	filter := bson.M{"_id": e.ID}
	err := col.FindOne(ctx, filter).Decode(&e)
	return err
}

/*
 * Updates the record with the passed one
 */
func (e *Event) UpdateEvent(db *mongo.Database, ue Event) (*mongo.UpdateResult, error) {
	col, ctx := GetColCtx(eventColName, db, 30)
	filter := bson.M{"_id": e.ID}
	update := bson.M{"$set": ue}
	result, err := col.UpdateOne(ctx, filter, update)
	return result, err
}
