/*
 * PrImBoard
 *
 * PrImBoard (Private Image Board) can be best described as an image board for all the picures and videos you have taken. You can invite users to the board and share specific images with them or your family members!
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserGroup struct {

	Id int64 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Creator string `json:"creator,omitempty"`

	TimestampCreation int64 `json:"timestamp_creation,omitempty"`

	Users []string `json:"users,omitempty"`

	Events []UserGroupEvents `json:"events,omitempty"`
}
